changelog:
  categories:
    - title: "Breaking Changes"
      labels:
        - "breaking-change"
    - title: "Features"
      labels:
        - "enhancement"
    - title: "Fixes"
      labels:
        - "bug"
    - title: "Documentation"
      labels:
        - "documentation"
    - title: "Security"
      labels:
        - "security"
    - title: "Maintenance"
      labels:
        - "dependencies"
    - title: "Other Changes"
      labels:
        - "*"
  exclude:
    labels:
      - "skip-changelog"
