name: autofix.ci

on:
  pull_request:
  push:

permissions:
  contents: write

jobs:
  prettier:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: HUSKY=0 npm ci

      - name: Format repository
        run: npm run format

      - name: Commit autofix changes
        uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a # v1
        with:
          commit-message: "Apply Prettier format"
